export const API_URLS = {
  baseURL: process.env.BASE_URL,
  categoryAll: "v1/category",
  categoryType: "v1/category/type",
  psychicDetails: "v1/users/professional/",
  psychicCategory: "v1/users/professional/",
  createSchedules: "v1/schedules",
  clientLogin: "v1/auth/client/login",
  availableSlots: "v1/schedules/available-slots/",
  checkSlot: "v1/schedules/check-slot/",
  explorePsychic: "v1/users/get-latest-professionals",
  clientRegister: "v1/auth/client/register",
  issues: "/v1/auth/issues",
  userCheckEmail: "/v1/users/check-email",
  walletScheduleDetail: "v1/wallet/schedule-payment-details",
};
